---
apiVersion: v1
kind: Namespace
metadata:
  name: tsfluentbit
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tsfluentbitusr
  namespace: tsfluentbit
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::252557384592:role/tsserviceaccounts3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tsfluentbit
  name: deployment-tsfluentbit
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-tsfluentbit
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-tsfluentbit
    spec:
      serviceAccountName: tsfluentbitusr
      containers:
      - image: tansong0091/httpd-oidc:0.2
        imagePullPolicy: Always
        name: app-tsfluentbit
        ports:
        - containerPort: 80
        volumeMounts:
        - name: logs
          mountPath: /usr/local/apache2/logs
      volumes:
      - name: logs
        hostPath:
          path: /var/log/tsfluentbithttpdlog
---
kind: Service
apiVersion: v1
metadata:
  name: tsfluentbit-service
  namespace: tsfluentbit
spec:
  selector:
    app.kubernetes.io/name: app-tsfluentbit
  ports:
  # Default port used by the image
  - port: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: tsfluentbitingress
  namespace: tsfluentbit
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
            serviceName: tsfluentbit-service
            servicePort: 80

